<a href="https://colab.research.google.com/github/AftabUdaipurwala/MachineLearningBasics/blob/ClassificationModels/Cross_Validation_K_Fold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()

In [10]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(digits.data,digits.target, test_size=0.3)

In [11]:
lr= LogisticRegression(random_state=123)
lr.fit(xtrain,ytrain)
lr.score(xtest,ytest)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9592592592592593

In [12]:
svc= SVC(random_state=123)
svc.fit(xtrain,ytrain)
svc.score(xtest,ytest)

0.9907407407407407

In [13]:
rf= RandomForestClassifier(random_state=123)
rf.fit(xtrain,ytrain)
rf.score(xtest,ytest)

0.9740740740740741

In [15]:
from sklearn.model_selection import KFold

In [17]:
kf= KFold(n_splits=3, random_state=123)
kf

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


KFold(n_splits=3, random_state=123, shuffle=False)

In [18]:
for train_index, test_index in kf.split(range(9)):
  print(train_index,test_index)
  

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [29]:
def get_score(model, xtrain,xtest,ytrain,ytest):
  model.fit(xtrain,ytrain)
  return model.score(xtest,ytest)

In [30]:
listing = [LogisticRegression(),SVC(),RandomForestClassifier()]
for i in listing:
  get_score(i, xtrain,xtest,ytrain,ytest)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [33]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)
scores_l =[]
scores_s=[]
scores_r=[]

for train_index, test_index in kf.split(digits.data):
  xtrain, xtest, ytrain, ytest = digits.data[train_index], digits.data[test_index],digits.target[train_index], digits.target[test_index]
  scores_l.append(get_score(LogisticRegression(),xtrain,xtest,ytrain,ytest))
  scores_s.append(get_score(SVC(),xtrain,xtest,ytrain,ytest))
  scores_r.append(get_score(RandomForestClassifier(),xtrain,xtest,ytrain,ytest))



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [38]:
scores_l,np.mean(scores_l)

([0.9232053422370617, 0.9415692821368948, 0.9148580968280468],
 0.9265442404006677)

In [39]:
scores_r,np.mean(scores_r)

([0.9382303839732888, 0.9532554257095158, 0.9282136894824707],
 0.9398998330550917)

In [40]:
scores_s, np.mean(scores_s)

([0.9666110183639399, 0.9816360601001669, 0.9549248747913188],
 0.9677239844184752)

In [49]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([0.92153589, 0.94156928, 0.91652755])

In [47]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(),digits.data,digits.target, cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [46]:
from sklearn.model_selection import cross_val_score
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3)

array([0.94156928, 0.95158598, 0.92654424])