<a href="https://colab.research.google.com/github/AftabUdaipurwala/MachineLearningBasics/blob/LinearRegression/Dummy_Variables_%26_One_Hot_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!ls '/content/drive/MyDrive/py-master/ML/5_one_hot_encoding/'

Exercise  homeprices.csv  one_hot_encoding.ipynb


In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('/content/drive/MyDrive/py-master/ML/5_one_hot_encoding/homeprices.csv')
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [6]:
# Get dummies method of Pandas library to be used for creating the dummmy variables
dum_var=pd.get_dummies(df.town)

In [10]:
merged = pd.concat([df,dum_var], axis=1)
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [13]:
# remove town & westwindsor  column so that we can use dummy variables . and get rid of dummy variables trap
final= merged.drop(['town','west windsor'], axis=1)
final

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [15]:
from sklearn.linear_model import LinearRegression 
model = LinearRegression()

In [21]:
x= final.drop(['price'], axis =1)
y= final['price']
x,y

(    area  monroe township  robinsville
 0   2600                1            0
 1   3000                1            0
 2   3200                1            0
 3   3600                1            0
 4   4000                1            0
 5   2600                0            0
 6   2800                0            0
 7   3300                0            0
 8   3600                0            0
 9   2600                0            1
 10  2900                0            1
 11  3100                0            1
 12  3600                0            1, 0     550000
 1     565000
 2     610000
 3     680000
 4     725000
 5     585000
 6     615000
 7     650000
 8     710000
 9     575000
 10    600000
 11    620000
 12    695000
 Name: price, dtype: int64)

In [20]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
model.predict([[2800,0,1]])

array([590775.63964739])

In [23]:
model.predict([[3400,0,0]])

array([681241.66845839])

In [24]:
model.score(x,y)

0.9573929037221873

In [25]:
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [26]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [29]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [35]:
x=dfle[['town','area']].values
y=dfle.price
x,y

(array([[   0, 2600],
        [   0, 3000],
        [   0, 3200],
        [   0, 3600],
        [   0, 4000],
        [   2, 2600],
        [   2, 2800],
        [   2, 3300],
        [   2, 3600],
        [   1, 2600],
        [   1, 2900],
        [   1, 3100],
        [   1, 3600]]), 0     550000
 1     565000
 2     610000
 3     680000
 4     725000
 5     585000
 6     615000
 7     650000
 8     710000
 9     575000
 10    600000
 11    620000
 12    695000
 Name: price, dtype: int64)

In [46]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='passthrough')


In [47]:
x=np.array(columnTransformer.fit_transform(x),dtype=np.str)

In [49]:
x =x[:,1:]

In [50]:
x

array([['0.0', '0.0', '2600.0'],
       ['0.0', '0.0', '3000.0'],
       ['0.0', '0.0', '3200.0'],
       ['0.0', '0.0', '3600.0'],
       ['0.0', '0.0', '4000.0'],
       ['0.0', '1.0', '2600.0'],
       ['0.0', '1.0', '2800.0'],
       ['0.0', '1.0', '3300.0'],
       ['0.0', '1.0', '3600.0'],
       ['1.0', '0.0', '2600.0'],
       ['1.0', '0.0', '2900.0'],
       ['1.0', '0.0', '3100.0'],
       ['1.0', '0.0', '3600.0']], dtype='<U32')

In [51]:
model.fit(x,y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:755: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  estimator=estimator)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [53]:
model.predict([[0,1,3400]])

array([681241.6684584])

Exercise # predict the price of used car by means of dummy variable
***bold text***

In [54]:
df = pd.read_csv('/content/drive/MyDrive/py-master/ML/5_one_hot_encoding/Exercise/carprices.csv')
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [57]:
dummies = pd.get_dummies(df['Car Model'])
dummies

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [59]:
merged = pd.concat([df,dummies],axis=1)

In [ ]:
merged= merged.drop(['Car Model','Mercedez Benz C class'],axis=1)
merged


In [65]:
merged.columns =['Mileage','prices','age','audi','bmw']
merged

Mileage  prices  age  audi  bmw
0     69000   18000    6     0    1
1     35000   34000    3     0    1
2     57000   26100    5     0    1
3     22500   40000    2     0    1
4     46000   31500    4     0    1
5     59000   29400    5     1    0
6     52000   32000    5     1    0
7     72000   19300    6     1    0
8     91000   12000    8     1    0
9     67000   22000    6     0    0
10    83000   20000    7     0    0
11    79000   21000    7     0    0
12    59000   33000    5     0    0

In [67]:
model.fit(merged[['Mileage','age','audi','bmw']],merged[['prices']])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [68]:
model.predict([[45000,4,0,0]])

array([[36991.31721061]])

In [69]:
model.predict([[86000,7,0,1]])

array([[11080.74313219]])

In [71]:
model.score(merged[['Mileage','age','audi','bmw']],merged[['prices']])

0.9417050937281083