<a href="https://colab.research.google.com/github/AftabUdaipurwala/MachineLearningBasics/blob/LinearRegression/MultipleLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [28]:
!ls '/content/drive/MyDrive/py-master/ML/2_linear_reg_multivariate/Exercise'

exercise_answer.ipynb  hiring.csv


In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('/content/drive/MyDrive/py-master/ML/2_linear_reg_multivariate/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [9]:
median_bedrooms=df.bedrooms.median()
median_bedrooms

4.0

In [14]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df.bedrooms

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [20]:
reg= linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
reg.coef_, reg.intercept_

(array([  112.06244194, 23388.88007794, -3231.71790863]), 221323.00186540396)

In [22]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [23]:
reg.predict([[2500,4,5]])

array([578876.03748933])

***Excercise for the Multiple linear regression tutorials***

In [29]:
df = pd.read_csv('/content/drive/MyDrive/py-master/ML/2_linear_reg_multivariate/Exercise/hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [41]:
!pip install word2number

In [46]:
from word2number import w2n

In [49]:
words= df.experience.to_list()
print(words)

[nan, nan, 'five', 'two', 'seven', 'three', 'ten', 'eleven']


In [72]:
for i in words[0:7]:
  if i == np.NaN:
     i = 'zero'
  x=w2n.word_to_num(i)
  print(x)

ValueError: ignored