<a href="https://colab.research.google.com/github/AftabUdaipurwala/MachineLearningBasics/blob/LinearRegression/MultipleLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [107]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [108]:
!ls '/content/drive/MyDrive/py-master/ML/2_linear_reg_multivariate/Exercise'

exercise_answer.ipynb  hiring.csv


In [109]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [110]:
df = pd.read_csv('/content/drive/MyDrive/py-master/ML/2_linear_reg_multivariate/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [111]:
median_bedrooms=df.bedrooms.median()
median_bedrooms

4.0

In [112]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df.bedrooms

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [113]:
reg= linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [114]:
reg.coef_, reg.intercept_

(array([  112.06244194, 23388.88007794, -3231.71790863]), 221323.00186540396)

In [115]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [116]:
reg.predict([[2500,4,5]])

array([578876.03748933])

***Excercise for the Multiple linear regression tutorials***

In [117]:
df = pd.read_csv('/content/drive/MyDrive/py-master/ML/2_linear_reg_multivariate/Exercise/hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [118]:
!pip install word2number

In [119]:
from word2number import w2n

In [120]:
df.experience=df.experience.fillna('zero')
x= round(np.mean(df['test_score(out of 10)']),0)
df['test_score(out of 10)']= df['test_score(out of 10)'].fillna(x)

In [121]:
words= df.experience.to_list()
print(words)

['zero', 'zero', 'five', 'two', 'seven', 'three', 'ten', 'eleven']


In [122]:
num = []
for i in df.experience:
  x = w2n.word_to_num(i)
  num.append(x)
print(num)
df['exp']=num
  


[0, 0, 5, 2, 7, 3, 10, 11]


In [125]:
df1 = df.iloc[:, 1:]
df1

test_score(out of 10)  interview_score(out of 10)  salary($)  exp
0                    8.0                           9      50000    0
1                    8.0                           6      45000    0
2                    6.0                           7      60000    5
3                   10.0                          10      65000    2
4                    9.0                           6      70000    7
5                    7.0                          10      62000    3
6                    8.0                           7      72000   10
7                    7.0                           8      80000   11

In [126]:
reg= linear_model.LinearRegression()
reg.fit(df1[['exp','test_score(out of 10)','interview_score(out of 10)']], df1['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [128]:
reg.coef_,reg.intercept_

(array([2812.95487627, 1845.70596798, 2205.24017467]), 17737.263464337702)

In [129]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [130]:
reg.predict([[12,10,10]])

array([92002.18340611])