<a href="https://colab.research.google.com/github/AftabUdaipurwala/MachineLearningBasics/blob/LinearRegression/Save_Model_Using_Joblib_And_Pickle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
!ls '/content/drive/MyDrive/py-master/ML/1_linear_reg/'

1_linear_regression.ipynb  error_equation.jpg  linear_equation.png
areas.csv		   Exercise	       linearReg.py
different_lines.JPG	   homeprices.csv      prediction.csv
equation.PNG		   homepricetable.JPG  scatterplot.JPG


In [8]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [44]:
df = pd.read_csv('/content/drive/MyDrive/py-master/ML/1_linear_reg/homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [45]:
reg= linear_model.LinearRegression()
reg.fit(df[['area']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [46]:
reg.coef_, reg.intercept_

(array([135.78767123]), 180616.43835616432)

In [47]:
reg.predict([[2000]])

array([452191.78082192])

In [48]:
import pickle

In [49]:
with open('model_pickle','wb') as f:
  pickle.dump(reg,f)

In [50]:
with open('model_pickle','rb') as f:
  mp = pickle.load(f)

In [51]:
mp.predict([[3000]])

array([587979.45205479])

In [52]:
from sklearn.externals import joblib

/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [54]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [56]:
mj=joblib.load('model_joblib')

In [58]:
mj.predict([[3000]])

array([587979.45205479])

In [59]:
mj.coef_

array([135.78767123])